# Generated by Django 4.2.11 on 2024-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_balance_remove_invoice_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='html_content',
            field=models.TextField(default=None),
        ),
    ]
